import {Inter} from 'next/font/google'
import './globals.css'
import Script from 'next/script'

const inter = Inter({subsets: ['latin']})

export const metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({children}) {
    return (
        <html lang="ru">
        <body className={inter.className}>

        <Script src="/jquery-3.7.1.min.js" />

        <div id={'app'}>
            {children}
        </div>
        </body>
        </html>
    )
}
